name: Run Tests and Check Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npx eslint src tests --ext .ts
      
      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Enforce minimum coverage
        run: |
          npx jest --coverage --coverageThreshold='{
            "global": {
              "branches": 70,
              "functions": 70,
              "lines": 70,
              "statements": 70
            }
          }'
